### ISSUE TITLE
Failed to build on with xcode 16.3 targetting iphoneos-18.4

### ISSUE THREAD

**Issue by MrCyjaneK** [hyle-team/zano#518]
The issue appeared after updating iphoneossdk to 18.4 (from 18.2) (and xcode from 16.2 to 16.3

```
In file included from /Users/user/work/monero_c/zano/contrib/zlib/zutil.c:10:
In file included from /Users/user/work/monero_c/zano/contrib/zlib/gzguts.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.4.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
/Users/user/work/monero_c/zano/contrib/zlib/zutil.h:140:33: note: expanded from macro 'fdopen'
  140 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
```

I'm using monero_c toolchain because iOS is not officially documented, and iOS build scripts ships precompiled binaries (so the issue won't occur)

Steps to reproduce:

```
1. xcrun --sdk iphoneos --show-sdk-path # make sure it ends with iPhoneOS18.4.sdk
2. git clone https://github.com/mrcyjanek/monero_c --recursive && cd monero_c
3. ./apply_patches.sh zano
4. ./build_single.sh zano aarch64-apple-ios -j1
```

**Comment by MrCyjaneK** [comment]
related: https://github.com/bulletphysics/bullet3/issues/4607

**Comment by Scenery21way** [comment]
try the lower llvm/clang version

**Comment by cryptozoidberg** [comment]
Missed this one, sorry @MrCyjaneK 
is this issue still present?
